### ISSUE TITLE
Add integration test for reverted `IN` and `NOT_IN`

### ISSUE THREAD

**Issue by mjalil** [Unleash/client-specification#77]
### Describe the feature request

Strategy constrinat specifications lacks a test case for testing reverted `IN` and `NOT_IN` constraint. I want to add it
it relates to [this issue](https://github.com/Unleash/unleash-client-dotnet/issues/195)

### Background

Reverted constraint does not work for `IN` and `NOT_IN` operators in some client SDKs (AFAIK in dotnet)
reported as a [bug](https://github.com/Unleash/unleash-client-dotnet/issues/195) in the repo `unleash-client-dotnet`
It needs some integration tests

**Comment by sjaanus** [comment]
New integration test added https://github.com/Unleash/client-specification/pull/78
