### ISSUE TITLE
Duplicated test description

### ISSUE THREAD

**Issue by dkuku** [Unleash/client-specification#89]
### Describe the bug

I'm working on elixir client and recent update started to throw errors.
Some testing frameworks don't allow duplicated test descriptions and there was recenty added a duplicate in #88 
```
        {
            "description": "F2.startsWith.caseInsensitve should be enabled",
            "context": {
                "properties": {
                    "customField": "test@example.com"
                }
            },
            "toggleName": "F2.startsWith.caseInsensitve",
            "expectedResult": true
        },
        {
            "description": "F2.startsWith.caseInsensitve should be enabled",
            "context": {
                "properties": {
                    "customField": "TEsT@example.com"
                }
            },
            "toggleName": "F2.startsWith.caseInsensitve",
            "expectedResult": true
        },
```

### Expected behavior

Test descriptions should be distinct so it's easier to find the actual failure

### Subscription type

None

### Hosting type

None

**Comment by chriswk** [comment]
Thank you for this report. I'll update the test description to clear this up. Sorry for the slip-up.

**Comment by chriswk** [comment]
Live with 5.1.6. Again, thank you for bringing this to our attention

**Comment by dkuku** [comment]
Thanks, this repo is very useful for external client libraries.
